FROM node:20.11.0-alpine

WORKDIR /app

COPY package*.json ./

RUN npm install

ARG REACT_APP_API_KEY
ARG REACT_APP_SUGGEST_API_KEY

ENV REACT_APP_API_KEY=$REACT_APP_API_KEY
ENV REACT_APP_SUGGEST_API_KEY=$REACT_APP_SUGGEST_API_KEY

COPY . ./

RUN npm run build

CMD cp -r build result_build
